version: '3.8'

services:
  php:
    build: .
    container_name: task_orm_php
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: php -S 0.0.0.0:8000 -t .
    ports:
      - "8080:8000"
    depends_on:
      - db
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    tty: true

  db:
    image: mysql:8.0
    container_name: task_orm_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mini_orm
      MYSQL_USER: ormuser
      MYSQL_PASSWORD: ormuser
    ports:
      - "3360:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

